# -*- coding: utf-8 -*-
"""CNN_CIFAR_10 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_xpxlmS8MolzDDmx8KaYGXX7QSbHhLe

# CIFAR10 with CNNs
Simple starter notebook to benchmark your own CNN with PyTorch on the CIFAR-10 dataset.

OBS.:

- The main code is basically done, so focus on training the models and searching for the best hyperparameters and architectures.
- You are not required to use this exact code or even the PyTorch library.
- It is recommended to use execution environments with GPU access (such as Google Colab), since larger models will take more time to train.
- Remember to document the history of your experiments and which results motivated the changes in subsequent experiments.
"""

!pip -q install optuna torchmetrics

import os, time, math, random
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

import torchvision
import torchvision.transforms as T
from torchvision.datasets import CIFAR10

import optuna
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix
)
import matplotlib.pyplot as plt
from tqdm import tqdm

#@title Testes com otimizadores

def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
set_seed(42)
device

mean = (0.4914, 0.4822, 0.4465)
std  = (0.2470, 0.2435, 0.2616)

train_tf = T.Compose([
    T.RandomHorizontalFlip(),
    T.RandomCrop(32, padding=4),
    T.ToTensor(),
    T.Normalize(mean, std),
])
test_tf  = T.Compose([
    T.ToTensor(),
    T.Normalize(mean, std),
])

data_root = "./data"
train_set = CIFAR10(root=data_root, train=True,  download=True, transform=train_tf)
val_set   = CIFAR10(root=data_root, train=False, download=True, transform=test_tf)

num_classes = 10
class_names = train_set.classes
len(train_set), len(val_set), class_names

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool  = nn.MaxPool2d(2,2)       # 32->16, 64->8
        self.fc1   = nn.Linear(64*8*8, 120)  # cuidado: se mudar pooling, atualize aqui
        self.fc2   = nn.Linear(120, 84)
        self.fc3   = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x))) # 32x16x16
        x = self.pool(F.relu(self.conv2(x))) # 64x8x8
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)  # logits

def make_optimizer(name, params, lr, momentum=None):
    if name == "Adam":
        return torch.optim.Adam(params, lr=lr)
    if name == "RMSprop":
        return torch.optim.RMSprop(params, lr=lr, momentum=0.9)
    if name == "SGD":
        return torch.optim.SGD(params, lr=lr, momentum=(momentum or 0.9), nesterov=True)
    raise ValueError(name)

def train_one_epoch(model, loader, optimizer, criterion):
    model.train()
    tot_loss, correct, total = 0.0, 0, 0
    for x,y in loader:
        x,y = x.to(device), y.to(device)
        optimizer.zero_grad()
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward(); optimizer.step()
        tot_loss += loss.item() * x.size(0)
        correct  += (logits.argmax(1)==y).sum().item()
        total    += x.size(0)
    return tot_loss/total, correct/total

@torch.no_grad()
def evaluate(model, loader, criterion):
    model.eval()
    tot_loss, correct, total = 0.0, 0, 0
    for x,y in loader:
        x,y = x.to(device), y.to(device)
        logits = model(x)
        loss = criterion(logits, y)
        tot_loss += loss.item() * x.size(0)
        correct  += (logits.argmax(1)==y).sum().item()
        total    += x.size(0)
    return tot_loss/total, correct/total

import pandas as pd

study_logs = []
def objective(trial):
    optimizer_name = trial.suggest_categorical("optimizer", ["Adam","SGD","RMSprop"])
    lr            = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    batch_size    = trial.suggest_categorical("batch_size", [32,64,128])
    momentum      = trial.suggest_float("momentum", 0.8, 0.99) if optimizer_name=="SGD" else None

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True,  num_workers=2, pin_memory=True)
    val_loader   = DataLoader(val_set,   batch_size=256,      shuffle=False, num_workers=2, pin_memory=True)

    model = CNN().to(device)
    optimizer = make_optimizer(optimizer_name, model.parameters(), lr, momentum)
    criterion = nn.CrossEntropyLoss()

    EPOCHS = 10
    epoch_times, tr_losses, va_losses = [], [], []
    best_va = 0.0

    for ep in range(EPOCHS):
        t0 = time.time()
        tr_loss, _ = train_one_epoch(model, train_loader, optimizer, criterion)
        va_loss, va_acc = evaluate(model, val_loader, criterion)
        epoch_times.append(time.time()-t0)
        tr_losses.append(tr_loss); va_losses.append(va_loss)
        best_va = max(best_va, va_acc)
        trial.report(va_acc, ep)
        if trial.should_prune():
            raise optuna.TrialPruned()

    study_logs.append({
        "trial": trial.number,
        "optimizer": optimizer_name,
        "lr": lr, "batch_size": batch_size, "momentum": momentum,
        "best_val_acc": best_va,
        "mean_epoch_time": float(np.mean(epoch_times)),
        "train_loss_std": float(np.std(tr_losses)),
        "val_loss_std": float(np.std(va_losses)),
    })
    return best_va

set_seed(42)
sampler = optuna.samplers.TPESampler(seed=42)
pruner  = optuna.pruners.MedianPruner(n_warmup_steps=3)
study   = optuna.create_study(direction="maximize", sampler=sampler, pruner=pruner)
study.optimize(objective, n_trials=15, show_progress_bar=True)

best_trial = study.best_trial
print("Melhor trial:", best_trial.number)
print("Melhores parâmetros:", best_trial.params)
print("Melhor val_acc:", best_trial.value)

df = pd.DataFrame(study_logs).sort_values("best_val_acc", ascending=False).reset_index(drop=True)
display(df.head(10))

plt.figure()
plt.scatter(df["lr"], df["best_val_acc"])
plt.xscale("log")
plt.xlabel("learning rate"); plt.ylabel("best val acc"); plt.title("Val Acc vs LR (Pessoa 1)")
plt.show()

plt.figure()
df.boxplot(column="best_val_acc", by="optimizer"); plt.suptitle("")
plt.title("Val Acc por Otimizador"); plt.xlabel("Otimizador"); plt.ylabel("best val acc")
plt.show()

plt.figure()
df.boxplot(column="mean_epoch_time", by="optimizer"); plt.suptitle("")
plt.title("Tempo Médio por Época por Otimizador"); plt.xlabel("Otimizador"); plt.ylabel("tempo (s)")
plt.show()

from torch.cuda.amp import autocast, GradScaler

cnn = CNN().to(device)

bs = best_trial.params.get("batch_size", 128)
train_loader = DataLoader(train_set, batch_size=bs, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_set,   batch_size=256, shuffle=False, num_workers=2, pin_memory=True)

EPOCHS = 100
base_lr = 0.1 if bs >= 128 else 0.05

optimizer = torch.optim.SGD(
    cnn.parameters(), lr=base_lr, momentum=0.9, nesterov=True, weight_decay=5e-4
)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
scaler = GradScaler(enabled=torch.cuda.is_available())

best_va, best_state = 0.0, None

for ep in range(EPOCHS):
    cnn.train()
    tr_loss, tr_correct, tr_total = 0.0, 0, 0
    t0 = time.time()

    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad(set_to_none=True)
        with autocast(enabled=torch.cuda.is_available()):
            logits = cnn(xb)
            loss = criterion(logits, yb)
        scaler.scale(loss).backward()
        scaler.step(optimizer); scaler.update()

        tr_loss += loss.item() * xb.size(0)
        tr_correct += (logits.argmax(1) == yb).sum().item()
        tr_total += xb.size(0)

    # val
    cnn.eval()
    va_loss, va_correct, va_total = 0.0, 0, 0
    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(device), yb.to(device)
            logits = cnn(xb)
            loss = criterion(logits, yb)
            va_loss += loss.item() * xb.size(0)
            va_correct += (logits.argmax(1) == yb).sum().item()
            va_total += xb.size(0)

    scheduler.step()

    train_acc = tr_correct / tr_total
    val_acc = va_correct / va_total
    print(f"[{ep+1:03d}/{EPOCHS}] lr={optimizer.param_groups[0]['lr']:.5f} "
          f"train_loss={(tr_loss/tr_total):.4f} train_acc={train_acc:.4f} "
          f"val_loss={(va_loss/va_total):.4f} val_acc={val_acc:.4f} ({time.time()-t0:.1f}s)")

    if val_acc > best_va:
        best_va = val_acc
        best_state = {k: v.cpu() for k, v in cnn.state_dict().items()}

print(f"Melhor val_acc: {best_va:.4f}")
cnn.load_state_dict(best_state)
cnn.eval()

"""### Defining the CNN model
Here we adapt the LeNet-5 architecture introduced in [*Gradient-based learning applied to document recognition*](https://ieeexplore.ieee.org/document/726791), originally developed to classify handwritten digits.

![lenet5](https://www.researchgate.net/publication/359784095/figure/fig2/AS:11431281079624737@1660789284522/Example-of-a-CNN-LeNet-5-14-is-able-to-identify-handwritten-digits-for-zip-code.png)


The main change we made here is the number of in/out channels, kernel sizes, padding, etc (enabling better results). It has 2 convolutional layers followed by 2 pooling (subsampling) layers. After the conv. blocks, we pass the feature maps through 2 hidden fully-connected layers to get the most activated neuron with the softmax function. If you want a more detailed explanation, [check this link](https://www.datasciencecentral.com/lenet-5-a-classic-cnn-architecture/) or reach us on Discord :)
"""

net = cnn  # se seu objeto for "model", troque aqui

# usa val_loader (ou test_loader se preferir)
eval_loader = val_loader

preds, gts = [], []
with torch.no_grad():
    for x, y in eval_loader:
        x = x.to(device); y = y.to(device)
        p = net(x).argmax(1)
        preds.extend(p.cpu().numpy()); gts.extend(y.cpu().numpy())

scores = {
    "accuracy": accuracy_score(gts, preds),
    "balanced_accuracy": balanced_accuracy_score(gts, preds),
    "precision_weighted": precision_score(gts, preds, average="weighted", zero_division=0),
    "recall_weighted": recall_score(gts, preds, average="weighted", zero_division=0),
    "f1_weighted": f1_score(gts, preds, average="weighted", zero_division=0),
}
print("Scores agregados:", {k: f"{v:.4f}" for k,v in scores.items()})

print("\nClassification report:")
print(classification_report(gts, preds, target_names=class_names, digits=4, zero_division=0))

# Matriz de confusão (com contagem + %)
labels_fix = list(range(10))
cm = confusion_matrix(gts, preds, labels=labels_fix)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
cm_norm = np.nan_to_num(cm_norm)

fig, ax = plt.subplots(figsize=(8,8))
im = ax.imshow(cm_norm, vmin=0.0, vmax=1.0)
ax.set_xticks(range(10)); ax.set_yticks(range(10))
ax.set_xticklabels(class_names, rotation=45, ha='right')
ax.set_yticklabels(class_names)
ax.set_xlabel("Predito"); ax.set_ylabel("Real")
ax.set_title("Matriz de Confusão (normalizada por classe)")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, f"{cm[i, j]}\n{cm_norm[i, j]*100:.1f}%", ha="center", va="center", fontsize=8)

fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
plt.tight_layout(); plt.show()

df.to_csv("pessoa1_busca_resultados.csv", index=False)
import json
with open("pessoa1_melhores_parametros.json","w") as f:
    json.dump(best_trial.params, f, indent=2)
print("Gerados: pessoa1_busca_resultados.csv, pessoa1_melhores_parametros.json")

#@title  Testes de Otimização da Arquitetura

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torchvision.datasets import CIFAR10
from sklearn import metrics
from tqdm import tqdm
import optuna

# Data Augmentation para treino
transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),      # flip horizontal aleatório
    transforms.RandomCrop(32, padding=4),  # crop aleatório com padding
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465),
                         (0.2470, 0.2435, 0.2616))
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465),
                         (0.2470, 0.2435, 0.2616))
])

train_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform_train)
test_dataset  = CIFAR10(root='./data', train=False, download=True, transform=transform_test)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=2)
test_loader  = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=2)

def objective(trial):
    # 🔧 Hiperparâmetros da arquitetura e do treinamento
    n_conv_layers = trial.suggest_int("n_conv_layers", 2, 4)
    filters = [trial.suggest_int(f"filters_l{i}", 32, 128, step=32) for i in range(n_conv_layers)]
    dense_units = trial.suggest_int("dense_units", 128, 512, step=128)
    kernel_size = trial.suggest_categorical("kernel_size", [3, 5])
    lr = trial.suggest_loguniform("lr", 1e-4, 1e-2)

    #  Criação dinâmica da CNN conforme parâmetros do trial
    layers = []
    in_channels = 3
    for i in range(n_conv_layers):
        out_channels = filters[i]
        layers.append(nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, padding=1))
        layers.append(nn.ReLU())
        layers.append(nn.BatchNorm2d(out_channels))
        layers.append(nn.MaxPool2d(2))
        in_channels = out_channels

    conv_part = nn.Sequential(*layers)

    # Calcula automaticamente o tamanho de entrada da camada densa
    with torch.no_grad():
        example = torch.zeros(1, 3, 32, 32)
        try:
            output_shape = conv_part(example).shape
            if output_shape[2] <= 1 or output_shape[3] <= 1:
                raise optuna.exceptions.TrialPruned()
            flatten_size = conv_part(example).view(1, -1).size(1)
        except RuntimeError:
            raise optuna.exceptions.TrialPruned()

    # Camadas totalmente conectadas
    model = nn.Sequential(
        conv_part,
        nn.Flatten(),
        nn.Linear(flatten_size, dense_units),
        nn.ReLU(),
        nn.Linear(dense_units, 10)
    ).cuda()

    #  Treinamento rápido
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    model.train()
    for epoch in range(15):
        running_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.cuda(), labels.cuda()
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        tqdm.write(f"Trial {trial.number} - Época {epoch+1}, Loss média: {running_loss/len(train_loader):.4f}")

    # 🧾 Avaliação no conjunto de teste
    model.eval()
    predictions, targets = [], []
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.cuda(), labels.cuda()
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            predictions.extend(predicted.cpu().numpy())
            targets.extend(labels.cpu().numpy())

    acc = metrics.accuracy_score(targets, predictions)
    trial.set_user_attr("num_params", sum(p.numel() for p in model.parameters()))
    return acc

# Execução do Optuna
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=20)

print(" Melhor acurácia:", study.best_value)
print("Melhores parâmetros encontrados:", study.best_params)
print(" Total de parâmetros:", study.best_trial.user_attrs["num_params"])

"""# Testes com Operação de Convolução

"""

!pip install optuna

import torch
import torchvision
import torchvision.transforms as transforms
import logging

batch_size = 32

transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.RandomRotation(15),
    transforms.RandomErasing(p=0.25, scale=(0.02, 0.2)),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])


train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform_train)

test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform_test)

#@title Loaders

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

logging.info("Datasets carregados e DataLoaders criados")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logging.info(f"Using device: {device}")

"""#Blocos Convolucao"""

import torch.nn as nn

# Padrão conv2d
class ConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
    def forward(self, x):
        return nn.ReLU()(self.conv(x))

# Depthwise separable convolution
class DepthwiseSeparableBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.depthwise = nn.Conv2d(in_channels, in_channels, kernel_size=3, groups=in_channels, padding=1)
        self.pointwise = nn.Conv2d(in_channels, out_channels, kernel_size=1)
    def forward(self, x):
        x = nn.ReLU()(self.depthwise(x))
        return nn.ReLU()(self.pointwise(x))

# Grouped convolution
class GroupedConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels, groups=2):
        super().__init__()
        # Handle the case where in_channels is 3 to avoid the error
        if in_channels == 3:
            groups = 1 # Set groups to 1 when in_channels is 3
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, groups=groups)
    def forward(self, x):
        return nn.ReLU()(self.conv(x))

# Dilated convolution
class DilatedConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels, dilation=2):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=dilation, dilation=dilation)
    def forward(self, x):
        return nn.ReLU()(self.conv(x))

# 1x1 convolution
class Conv1x1Block(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)
    def forward(self, x):
        return nn.ReLU()(self.conv(x))

# Residual block
class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
        self.shortcut = nn.Sequential()
        if in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=1, bias=False),
                nn.BatchNorm2d(out_channels)
            )
    def forward(self, x):
        return nn.ReLU()(self.shortcut(x) + self.conv(x))

"""#Modelo CNN"""

class CNN(nn.Module):
    def __init__(self, conv_block): # Add conv_block as an argument
        super(CNN, self).__init__()
        self.conv_block = conv_block # Store conv_block as an instance variable

        # Defining convolution blocks with dilation using the passed conv_block
        # These will be replaced by the dynamic layers in the objective_dynamic_hp function
        self.conv1 = self.conv_block(3, 32)
        self.conv2 = self.conv_block(32, 64)

        # Defining pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Defining fully-connected layers - Adjust input size based on dilated conv output
        # The output size after conv1 with padding=1, dilation=1 and pool (kernel=2, stride=2) is 32/2 = 16
        # The output size after conv2 with padding=2, dilation=2 and pool (kernel=2, stride=2) needs to be recalculated.
        # Output size formula for Conv2d: (InputSize - KernelSize - (KernelSize - 1) * (Dilation - 1) + 2 * Padding) / Stride + 1
        # Output size after conv2: (16 - 3 - (3 - 1) * (2 - 1) + 2 * 2) / 1 + 1 = (16 - 3 - 2 + 4) / 1 + 1 = 15 + 1 = 16
        # Output size after pool: 16 / 2 = 8
        self.fc_hidden1 = nn.Linear(64 * 8 * 8, 120) # Input size remains 64 * 8 * 8
        self.fc_hidden2 = nn.Linear(120, 84)
        self.fc_output = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(nn.ReLU()(self.conv1(x)))
        x = self.pool(nn.ReLU()(self.conv2(x)))
        x = x.view(x.size(0), -1) # flatten to input into fc layers
        x = nn.ReLU()(self.fc_hidden1(x))
        x = nn.ReLU()(self.fc_hidden2(x))
        x = self.fc_output(x)
        return x

"""#Treinamento

"""

from tqdm import tqdm

def train_and_evaluate(model, optimizer, criterion, train_loader, test_loader, device):
    model.to(device)
    num_epochs = 20

    for epoch in tqdm(range(num_epochs), desc="Treinando modelo", unit="época"):
        model.train()
        running_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        avg_loss = running_loss / len(train_loader)
        logging.info(f"Época [{epoch+1}/{num_epochs}] — Loss médio: {avg_loss:.4f}")

    # Avaliação
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = correct / total
    logging.info(f"Acurácia final: {accuracy:.4f}")
    return accuracy

"""#Optuna

"""

import optuna
import logging
from optuna.pruners import MedianPruner

study_type = optuna.create_study(
    direction="maximize",
    pruner=MedianPruner(n_startup_trials=2, n_warmup_steps=3, interval_steps=1)
)

def objective_conv_type(trial):
    conv_type = trial.suggest_categorical("conv_type", [
        "standard", "depthwise", "grouped", "dilated", "conv1x1", "residual"
    ])

    # Escolhe o bloco de convolução
    if conv_type == "standard":
        conv_block = ConvBlock
    elif conv_type == "depthwise":
        conv_block = DepthwiseSeparableBlock
    elif conv_type == "grouped":
        conv_block = lambda in_c, out_c: GroupedConvBlock(in_c, out_c, groups=2)
    elif conv_type == "dilated":
        conv_block = lambda in_c, out_c: DilatedConvBlock(in_c, out_c, dilation=2)
    elif conv_type == "conv1x1":
        conv_block = Conv1x1Block
    elif conv_type == "residual":
        conv_block = ResidualBlock

    # Cria o modelo e define otimizador/perda
    model = CNN(conv_block).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    epochs = 15
    for epoch in tqdm(range(epochs), desc=f"Trial {trial.number} - {conv_type}", leave=False):
        model.train()
        running_loss = 0.0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        # Avaliação parcial
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        acc = correct / total
        trial.report(acc, epoch)

        # Early stopping (pruning)
        if trial.should_prune():
            logging.info(f"⏭️ Trial {trial.number} ({conv_type}) prune na epoch {epoch+1} - acc={acc:.4f}")
            raise optuna.TrialPruned()

        logging.info(f"Trial {trial.number} ({conv_type}) - Epoch {epoch+1}/{epochs} - Loss={running_loss/len(train_loader):.4f} - Acc={acc:.4f}")

    return acc


# Executa a otimização
study_type.optimize(objective_conv_type, n_trials=20, show_progress_bar=True)

best_conv_type = study_type.best_trial.params['conv_type']
logging.info(f"🏆 Melhor tipo de convolução encontrado: {best_conv_type}")

import pandas as pd

# Extrai resultados do estudo
df_conv = study_type.trials_dataframe(attrs=("value", "params", "state"))

# Garante que o nome do parâmetro está correto
if "params_conv_type" not in df_conv.columns:
    raise ValueError("A coluna 'params_conv_type' não foi encontrada — verifique o nome do parâmetro no estudo.")

df_conv.rename(columns={"params_conv_type": "conv_type"}, inplace=True)

# --- Tabela 1: Quantidade de trials prunadas por tipo de bloco ---
df_pruned = df_conv[df_conv["state"] == "PRUNED"]
tabela_pruned = (
    df_pruned["conv_type"]
    .value_counts()
    .rename_axis("Tipo de Convolução")
    .reset_index(name="Trials Prunadas")
)

# --- Tabela 2: Performance das trials completas ---
df_complete = df_conv[df_conv["state"] == "COMPLETE"]
tabela_perf = (
    df_complete.groupby("conv_type")["value"]
    .agg(["mean", "std", "count"])
    .rename(columns={
        "mean": "Acurácia Média",
        "std": "Desvio Padrão",
        "count": "Trials Completas"
    })
    .reset_index()
    .sort_values("Acurácia Média", ascending=False)
)

# Exibição formatada
print("\n📉 Tabela 1 - Trials Prunadas por Tipo de Convolução:\n")
print(tabela_pruned.to_string(index=False))

print("\n📊 Tabela 2 - Performance das Trials Completas:\n")
print(tabela_perf.round(4).to_string(index=False))

"""#Otimizando melhor resultado

"""

import optuna
from optuna.exceptions import TrialPruned
import logging
from tqdm import tqdm

logging.info(f"Iniciando otimização de hiperparâmetros para o tipo {best_conv_type}...")

def objective_dynamic_hp(trial):
    # Hiperparâmetros
    # Narrowing the search space based on common practices and the best conv type being 'standard'
    lr = trial.suggest_float("lr", 5e-4, 5e-3, log=True) # Narrowed learning rate range
    dropout_rate = trial.suggest_float("dropout_rate", 0.1, 0.4) # Narrowed dropout range
    hidden1 = trial.suggest_int("hidden1", 100, 200) # Narrowed hidden layer 1 size
    hidden2 = trial.suggest_int("hidden2", 50, 100) # Narrowed hidden layer 2 size

    # For 'standard' conv type, we will use a fixed number of blocks as defined in the CNN class
    num_blocks = 1 # Fixed number of blocks for standard CNN

    # Choose the convolution block type based on the best result from the first study
    # This part remains the same as we are focusing on the best_conv_type
    if best_conv_type == "standard":
        conv_block = ConvBlock
    elif best_conv_type == "depthwise":
        conv_block = DepthwiseSeparableBlock
    elif best_conv_type == "grouped":
        conv_block = lambda in_c, out_c: GroupedConvBlock(in_c, out_c, groups=2)
    elif best_conv_type == "dilated":
        conv_block = lambda in_c, out_c: DilatedConvBlock(in_c, out_c, dilation=2)
    elif best_conv_type == "conv1x1":
        conv_block = Conv1x1Block
    elif best_conv_type == "residual":
        conv_block = ResidualBlock
    else:
        # Fallback to standard if best_conv_type is unexpectedly something else
        conv_block = ConvBlock


    # Modelo with a fixed number of blocks for the standard CNN
    class DynamicCNN(nn.Module):
        def __init__(self):
            super().__init__()
            in_channels = 3
            out_channels = 32
            layers = []

            # Calculate initial spatial dimensions
            h, w = 32, 32

            # Assuming 2 convolutional blocks followed by pooling as in the original CNN class for standard
            layers.append(conv_block(in_channels, out_channels))
            if h >= 2 and w >= 2:
                layers.append(nn.MaxPool2d(2, 2))
                h //= 2
                w //= 2
            in_channels = out_channels
            out_channels = 64 # Second conv layer output channels

            layers.append(conv_block(in_channels, out_channels))
            if h >= 2 and w >= 2:
                 layers.append(nn.MaxPool2d(2, 2))
                 h //= 2
                 w //= 2


            self.features = nn.Sequential(*layers)

            # Dynamic flatten calculation based on the fixed architecture
            with torch.no_grad():
                dummy_input = torch.randn(1, 3, 32, 32)
                flattened = self.features(dummy_input).view(1, -1).size(1)


            self.fc1 = nn.Linear(flattened, hidden1)
            self.dropout = nn.Dropout(dropout_rate)
            self.fc2 = nn.Linear(hidden1, hidden2)
            self.fc3 = nn.Linear(hidden2, 10)

        def forward(self, x):
            x = self.features(x)
            x = x.view(x.size(0), -1)
            x = nn.ReLU()(self.fc1(x))
            x = self.dropout(x)
            x = nn.ReLU()(self.fc2(x))
            x = self.fc3(x)
            return x


    # Instantiate model and optimizer
    model = DynamicCNN().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    # Training with pruning
    num_epochs = 20
    best_acc = 0.0

    for epoch in tqdm(range(num_epochs), desc="Treinando modelo", leave=False):
        # Train for one epoch
        model.train()
        running_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        # Evaluation
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()
        acc = correct / total
        best_acc = max(best_acc, acc)

        # Report progress to Optuna
        trial.report(acc, step=epoch)

        # Prune if performing poorly
        if trial.should_prune():
            logging.info(f"Trial pruned at epoch {epoch+1} (acc={acc:.4f})")
            raise TrialPruned()

    logging.info(
        f"Trial: lr={lr:.5f}, h1={hidden1}, h2={hidden2}, "
        f"drop={dropout_rate:.2f} → acc={best_acc:.4f}"
    )
    return best_acc


# Study with pruning enabled
# We can keep the same study object or create a new one if we want to completely restart the search
# For now, let's create a new study to focus the search on the narrowed space
study_hp = optuna.create_study(
    direction="maximize",
    pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5)
)
study_hp.optimize(objective_dynamic_hp, n_trials=15, show_progress_bar=True)

logging.info(f"Best hyperparameters for {best_conv_type}: {study_hp.best_trial.params}")

import optuna
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import optuna.visualization as vis

# Gráficos nativos do Optuna
vis.plot_optimization_history(study_hp).show()
vis.plot_param_importances(study_hp).show()

# ---- Gráfico de correlação dos hiperparâmetros ----

# Extrai os dados dos trials para um DataFrame
df_trials = study_hp.trials_dataframe(attrs=("value", "params", "state"))

# Remove trials não concluídos
df_trials = df_trials[df_trials["state"] == "COMPLETE"]

# Remove colunas desnecessárias
df_trials = df_trials.drop(columns=["state"])

# Calcula a matriz de correlação
corr = df_trials.corr(numeric_only=True)

# Plota o mapa de calor
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlação entre Hiperparâmetros e Acurácia (value)")
plt.show()

"""<h2> Teste : Controlando a estabilidade e overfiting <h2>"""

import os, random, time, numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

MEAN, STD = (0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)

train_tf = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

eval_tf = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

train_full_aug   = datasets.CIFAR10("./data", train=True,  download=True, transform=train_tf)
train_full_clean = datasets.CIFAR10("./data", train=True,  download=True, transform=eval_tf)
test_ds          = datasets.CIFAR10("./data", train=False, download=True, transform=eval_tf)

g = torch.Generator().manual_seed(SEED)
perm = torch.randperm(len(train_full_aug), generator=g)
val_idx, train_idx = perm[:5000], perm[5000:]

train_ds = Subset(train_full_aug,   train_idx)   # AUGMENT
val_ds   = Subset(train_full_clean, val_idx)     # SEM AUGMENT

BATCH_SIZE = 128
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print("Tamanhos ->", len(train_ds), len(val_ds), len(test_ds))

class CNN3(nn.Module):
    def __init__(self, p=0.2, use_bn=True, num_classes=10, kernel_size=3):
        super().__init__()
        ks = kernel_size; pad = ks // 2

        def block(cin, cout):
            layers = [nn.Conv2d(cin, cout, ks, padding=pad, bias=False)]
            if use_bn: layers.append(nn.BatchNorm2d(cout))
            layers += [nn.ReLU(inplace=True),
                       nn.Conv2d(cout, cout, ks, padding=pad, bias=False)]
            if use_bn: layers.append(nn.BatchNorm2d(cout))
            layers += [nn.ReLU(inplace=True)]
            return nn.Sequential(*layers)

        self.features = nn.Sequential(
            block(3, 64), nn.MaxPool2d(2), nn.Dropout(p),
            block(64,128), nn.MaxPool2d(2), nn.Dropout(p),
            block(128,256), nn.MaxPool2d(2), nn.Dropout(p),
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Dropout(p),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.head(x)
        return x

DROPOUT = 0.2; USE_BN = True; KERNEL = 3
model = CNN3(p=DROPOUT, use_bn=USE_BN, kernel_size=KERNEL).to(device)
model

from torch.optim.lr_scheduler import LinearLR, SequentialLR, CosineAnnealingLR

def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    total_loss, y_true, y_pred = 0.0, [], []
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        loss = criterion(logits, y)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * x.size(0)
        y_true.extend(y.tolist())
        y_pred.extend(logits.argmax(1).tolist())
    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(y_true, y_pred)
    return avg_loss, acc

@torch.no_grad()
def evaluate(model, loader, criterion):
    model.eval()
    total_loss, y_true, y_pred = 0.0, [], []
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        loss = criterion(logits, y)
        total_loss += loss.item() * x.size(0)
        y_true.extend(y.tolist())
        y_pred.extend(logits.argmax(1).tolist())
    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(y_true, y_pred)
    return avg_loss, acc

def fit(model, train_loader, val_loader,
        epochs=50, base_lr=0.1, momentum=0.9, weight_decay=5e-4,
        patience=12, min_epochs=20, label_smoothing=0.1, use_warmup=True):

    criterion = nn.CrossEntropyLoss(label_smoothing=label_smoothing)
    optimizer = torch.optim.SGD(model.parameters(), lr=base_lr, momentum=momentum,
                                weight_decay=weight_decay, nesterov=True)

    if use_warmup and epochs > 10:
        warmup = LinearLR(optimizer, start_factor=0.2, total_iters=5)
        cosine = CosineAnnealingLR(optimizer, T_max=epochs-5)
        scheduler = SequentialLR(optimizer, [warmup, cosine], milestones=[5])
    else:
        scheduler = CosineAnnealingLR(optimizer, T_max=epochs)

    history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}
    best_val = float("inf")
    best_state = None
    wait = 0

    for ep in range(1, epochs+1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer)
        vl_loss, vl_acc = evaluate(model, val_loader, criterion)

        history["train_loss"].append(tr_loss); history["train_acc"].append(tr_acc)
        history["val_loss"].append(vl_loss);   history["val_acc"].append(vl_acc)

        print(f"Epoch {ep:03d} | train_loss={tr_loss:.4f} train_acc={tr_acc:.4f} | "
              f"val_loss={vl_loss:.4f} val_acc={vl_acc:.4f} | lr={scheduler.get_last_lr()[0]:.5f}")

        improved = vl_loss < (best_val - 1e-4)
        if improved:
            best_val = vl_loss
            best_state = {k: v.detach().cpu() for k, v in model.state_dict().items()}
            wait = 0
        else:
            if ep >= min_epochs:
                wait += 1
                if wait >= patience:
                    print("Early stopping!")
                    break

        scheduler.step()

    if best_state is not None:
        model.load_state_dict(best_state)

    os.makedirs("checkpoints", exist_ok=True)
    torch.save(model.state_dict(), "checkpoints/cnn3_pessoa3_best.pt")
    print("Checkpoint salvo em checkpoints/cnn3_pessoa3_best.pt")
    return model, history

def plot_history(h):
    epochs = range(1, len(h["train_loss"])+1)
    plt.figure()
    plt.plot(epochs, h["train_loss"], label="train_loss")
    plt.plot(epochs, h["val_loss"], label="val_loss")
    plt.xlabel("Época"); plt.ylabel("Loss"); plt.legend(); plt.title("Loss: train vs val"); plt.show()

    plt.figure()
    plt.plot(epochs, h["train_acc"], label="train_acc")
    plt.plot(epochs, h["val_acc"], label="val_acc")
    plt.xlabel("Época"); plt.ylabel("Acurácia"); plt.legend(); plt.title("Accuracy: train vs val"); plt.show()

    plt.figure()
    gap = np.array(h["train_acc"]) - np.array(h["val_acc"])
    plt.plot(epochs, gap, label="train_acc - val_acc")
    plt.xlabel("Época"); plt.ylabel("Gap de acurácia"); plt.legend(); plt.title("Gap (overfitting)"); plt.show()

EPOCHS = 50; BASE_LR = 0.1; MOMENTUM = 0.9; WEIGHT_DECAY = 5e-4; PATIENCE = 12; MIN_EPOCHS = 20

model = model.to(device)
model, history = fit(model, train_loader, val_loader,
                     epochs=EPOCHS, base_lr=BASE_LR, momentum=MOMENTUM,
                     weight_decay=WEIGHT_DECAY, patience=PATIENCE,
                     min_epochs=MIN_EPOCHS, label_smoothing=0.1, use_warmup=True)

plot_history(history)
mean_gap = float(np.mean(np.array(history["train_acc"]) - np.array(history["val_acc"])))
val_loss_std = float(np.std(history["val_loss"]))
print(f"Mean gap (train_val): {mean_gap:.4f} | Std(val_loss): {val_loss_std:.4f}")

@torch.no_grad()
def evaluate_test(model, loader):
    model.eval()
    y_true, y_pred = [], []
    total_loss = 0.0
    crit = nn.CrossEntropyLoss()
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        loss = crit(logits, y)
        total_loss += loss.item() * x.size(0)
        y_true.extend(y.tolist())
        y_pred.extend(logits.argmax(1).tolist())
    test_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(y_true, y_pred)
    return test_loss, acc, np.array(y_true), np.array(y_pred)

if os.path.exists("checkpoints/cnn3_pessoa3_best.pt"):
    model.load_state_dict(torch.load("checkpoints/cnn3_pessoa3_best.pt", map_location=device))

test_loss, test_acc, y_true, y_pred = evaluate_test(model, test_loader)
print(f"TEST | loss={test_loss:.4f} acc={test_acc:.4f}")

classes = test_ds.classes
print(classification_report(y_true, y_pred, target_names=classes, digits=3))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6,5))
plt.imshow(cm, interpolation='nearest')
plt.title("Matriz de Confusão - Teste")
plt.colorbar(); plt.xticks(range(len(classes)), classes, rotation=45)
plt.yticks(range(len(classes)), classes)
plt.tight_layout(); plt.xlabel("Predito"); plt.ylabel("Real")
plt.show()

"""# You can change/optimize this as you want
- Automatic hyperparameters optimization (Optuna)
- Regularization techniques (tip: try dropout)
- Use other convolution combinations (e.g. ResNet blocks)
- Validation set to track metrics during epochs
- Transform input data
- ...
"""